// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhYogA96rBt8zMUwCdR4lqgqBlICOqDE',
    appId: '1:406475018252:web:b6981929f25d3170fe5e29',
    messagingSenderId: '406475018252',
    projectId: 'asistente-presupuesto',
    authDomain: 'asistente-presupuesto.firebaseapp.com',
    storageBucket: 'asistente-presupuesto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhkOrLjAYYpSuZnXbmznFOv1fgrYVg1Ak',
    appId: '1:406475018252:android:7473e8c495d4b99afe5e29',
    messagingSenderId: '406475018252',
    projectId: 'asistente-presupuesto',
    storageBucket: 'asistente-presupuesto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCluiFE0LGSPUFf7-h8Z965Y8yCKVauUz4',
    appId: '1:406475018252:ios:9e7c96938e242aaefe5e29',
    messagingSenderId: '406475018252',
    projectId: 'asistente-presupuesto',
    storageBucket: 'asistente-presupuesto.firebasestorage.app',
    iosBundleId: 'com.example.asistentePresupuesto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCluiFE0LGSPUFf7-h8Z965Y8yCKVauUz4',
    appId: '1:406475018252:ios:9e7c96938e242aaefe5e29',
    messagingSenderId: '406475018252',
    projectId: 'asistente-presupuesto',
    storageBucket: 'asistente-presupuesto.firebasestorage.app',
    iosBundleId: 'com.example.asistentePresupuesto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALhYogA96rBt8zMUwCdR4lqgqBlICOqDE',
    appId: '1:406475018252:web:b2a8389b61bb33e5fe5e29',
    messagingSenderId: '406475018252',
    projectId: 'asistente-presupuesto',
    authDomain: 'asistente-presupuesto.firebaseapp.com',
    storageBucket: 'asistente-presupuesto.firebasestorage.app',
  );
}
